on: [push]

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'update'
          classpath: "example/mysql-connector-java-8.0.17.jar" 
          driver: "com.mysql.cj.jdbc.Driver"
          changeLogFile: 'example/samplechangelog.sql'
          username: "u632645567_pruebas"
          password: "Diego123*-*"
          url: "jdbc:mysql://149.62.37.204:3306/u632645567_pruebas"
