on:
  push:
    branches:
      - main

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    env:
        BUCKETTEMPLATES: dev-merchant-platform-artifacts-218299108648
        ECRNAME: encrypt-file #El nombre debe ser igual al definido en el project template
        FOO : date +%m%d%H%M%Y.%S
    steps:
      - name: Test
        run: |
          echo ${FOO}
         
