on: [push]

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'update'
          classpath: "example/mariadb-java-client-2.7.1.jar"  
          changeLogFile: 'example/samplechangelog.sql'
          username: "u632645567_pruebas"
          password: "Diego123*-*"
          url: "jdbc:mariadb://149.62.37.204:3306/u632645567_pruebas"
