on: [push]

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'update'
          classpath: 'example'
          changeLogFile: 'samplechangelog.sql'
          username: "postgres"
          password: "admin"
          url: "dev-merchant-platform-data-dbinstance.cpdprsgplcjh.us-east-1.rds.amazonaws.com"
