on:
  push:
    branches:
      - main

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "AKIAQJZNGEWM4TU3BQER"
          aws-secret-access-key: "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"
          aws-region: us-east-1
      - name: Set up / Open Tunnel
        run: |
          sudo apt install -y putty
          aws s3 cp s3://merchantkey/XX_AP_UPL_MERCHANT_DOCS_NPRD_.key XX_AP_UPL_MERCHANT_DOCS_NPRD_.key

      - uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'update'
          classpath: "example/mariadb-java-client-2.7.1.jar"  
          changeLogFile: 'example/samplechangelog.sql'
          username: "u632645567_pruebas"
          password: "Diego123*-*"
          url: "jdbc:mariadb://149.62.37.204:3306/u632645567_pruebas"
      
