on:
  push:
    branches:
      - main

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    env:
        BUCKETTEMPLATES: dev-merchant-platform-artifacts-218299108648
        ECRNAME: encrypt-file #El nombre debe ser igual al definido en el project template
        FOO : ${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Test
        run: |
          echo ${FOO}
         
