on:
  push:
    branches:
      - main

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "AKIAQJZNGEWMR2XSRKWS"
          aws-secret-access-key: "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"
          aws-region: us-east-1
      - name: Test
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 218299108648.dkr.ecr.us-east-1.amazonaws.com
          cd ./src/lambdas_container/encrypt_files/
          docker build -t $ECRNAME .
          aws ecr create-repository --repository-name $ECRNAME --image-scanning-configuration scanOnPush=true --image-tag-mutability MUTABLE || echo "it is possible that the ecr is already created"
          docker tag  $ECRNAME:latest 218299108648.dkr.ecr.us-east-1.amazonaws.com/$ECRNAME:latest
          docker push 218299108648.dkr.ecr.us-east-1.amazonaws.com/$ECRNAME:latest
          cd ../../../

