on: [push]

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v2
        with:
          operation: 'update'
          classpath: 'example'
          changeLogFile: 'samplechangelog.sql'
          username: "u632645567_pruebas"
          password: "Diego123*-*"
          url: "sql542.main-hosting.eu"
