on:
  push:
    branches:
      - main

jobs:
  test-liquibase-action:
    runs-on: ubuntu-latest
    name: Test Liquibase Action
    
    env:
        BUCKETTEMPLATES: dev-merchant-platform-artifacts-218299108648
        ECR_ACCOUNT: 218299108648.dkr.ecr.us-east-1.amazonaws.com 
        ECRNAME: encrypt-file
    steps:
      - name: Get the datetime string
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYYMMDDHHmmss'
      - name: Usage
        run: |
          echo $ECR_ACCOUNT/$ECRNAME:${{ steps.time.outputs.time }}
          echo ${{ steps.time.outputs.time }}
         
